server.port=8080

#Spring Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d8122qpj2pic73bjk0ig-a:5432/demo_play_db_njzk
spring.datasource.username:alan
spring.datasource.password:b3RsVUKmIFKxoIE60KXB9XgdzQyDoyQq

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

langchain4j.open-ai.chat-model.api-key=demo
